# name: GitHub-Profile-3D-Contrib

# on:
#   schedule: # 03:00 JST == 18:00 UTC
#     - cron: '0 18 * * *'
#   workflow_dispatch:

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     name: generate-github-profile-3d-contrib
#     steps:
#       - uses: actions/checkout@v3
#       - uses: yoshi389111/github-profile-3d-contrib@0.7.1
#         env:
#           GITHUB_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
#           USERNAME: ${{ github.repository_owner }}
#       - name: Commit & Push
#         run: |
#           git config user.name github-actions
#           git config user.email github-actions@github.com
#           git add -A .
#           git commit -m "generated"
#           git push
name: GitHub-Profile-3D-Contrib

on:
  schedule: # 03:00 JST == 18:00 UTC
    - cron: '0 18 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v3
      - name: Set GITHUB_TOKEN environment variable
        run: echo "GITHUB_TOKEN=${{ secrets.REPO_ACCESS_TOKEN }}" >> $GITHUB_ENV
      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          USERNAME: ${{ github.repository_owner }}
      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A .
          git commit -m "generated"
          git push
